version: "3.7"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./.data:/home
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres-storage:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  metabase:
    image: metabase/metabase
    environment:
      MB_JETTY_PORT: 80
      MB_DB_FILE: "/metabase-data/metabase.db"
    ports:
      - 80:80
    volumes:
      - metabase-storage:/metabase-data
    depends_on:
      postgres:
        condition: service_healthy
  adminer:
    image: adminer
    restart: always
    ports:
      - 8765:8080
  financials:
    build: './financials/'
    volumes:
      - node_volumes:/usr/src/app/node_volumes
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=station
      - POSTGRES_PASSWORD=${PG_PASSWORD}

volumes:
  metabase-storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .data/metabase
  postgres-storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .data/postgres
  node_volumes:
