version: "3.7"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    ports:
      - 5432:5432
    volumes:
      - $PWD/.data:/home
      - postgres-storage:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guest"]
      interval: 10s
      timeout: 5s
      retries: 5
  metabase:
    image: metabase/metabase
    ports:
      - 3000:3000
    network_mode: "host"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8765:8080
