version: "3.7"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      API_USER: ${API_USER:?}
      API_PASS: ${API_PASS:?}

    ports:
      - 5432:5432
    volumes:
      - ./.data:/home
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres-storage:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U guest" ]
      interval: 10s
      timeout: 5s
      retries: 5
  metabase:
    image: metabase/metabase
    environment:
      MB_JETTY_PORT: 80
    ports:
      - 80:80
    depends_on:
      postgres:
        condition: service_healthy
  adminer:
    image: adminer
    restart: always
    ports:
      - 8765:8080

volumes:
  metabase-storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PWD/.data/metabase
  postgres-storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .data/postgres
