version: "3.7"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    ports:
      - 5432:5432
    volumes:
      - $PWD/.data:/home
  metabase:
    image: metabase/metabase
    ports:
      - 3000:3000
    network_mode: "host"
